### ISSUE TITLE
抖音解析无水印的接口地址是多少可以提供一下吗

### ISSUE THREAD

**Issue by akkuan** [fly-studio/douyin-downloader#1]
感谢，自己最近也在学爬虫，但是FD抓不到抖音的数据。

**Comment by fly-studio** [comment]
1. 将抖音安装到Android模拟器中
2. 开启Fiddler的HTTPS抓取和代理
4. 模拟器设置代理，输入Fiddler的IP和端口
5. 看抓取到的HTTP数据即可

**Comment by akkuan** [comment]
谢谢，已经抓到了 只是抖音的as mas cp这些算法没法拿到规则。
