### ISSUE TITLE
下载不了，进度条不动

### ISSUE THREAD

**Issue by LvanCham** [fly-studio/douyin-downloader#3]

**Comment by LvanCham** [comment]
6.0以上 缺少动态申请 给你补上了 OK

**Comment by fly-studio** [comment]
不好意思啊，我一直用的debug版本。您要不PR您的修复代码一下？

**Comment by qiuliliang** [comment]
还没提交是不 还是下载不了

**Comment by fly-studio** [comment]
建议安装debug版本 都无需签名，一样的用

**Comment by qiuliliang** [comment]
没事了 我手动设置权限先

**Comment by fly-studio** [comment]
加了询问权限，在release页面下载DEBUG包就可以了

**Comment by fly-studio** [comment]
[latest release](https://github.com/fly-studio/douyin-downloader/releases/latest) 已经添加
