### ISSUE TITLE
/opt/MonkeyDev/bin/md: No such file or directory

### ISSUE THREAD

**Issue by TonyMistark** [fly-studio/douyin-downloader#6]
line 2: /opt/MonkeyDev/bin/md: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

需要安装什么依赖吗？
不是oc选手，见谅。

**Comment by TonyMistark** [comment]
发错地儿了，打扰了

**Comment by HappaNetwork** [comment]
大佬教教怎么搞
