### ISSUE TITLE
2019年5月29日 今天抖音更新了 获取不到了 你看下你能不能在更新一下

### ISSUE THREAD

**Issue by 5wcx** [fly-studio/douyin-downloader#7]

**Comment by fly-studio** [comment]
抖音 v6.3.0  2019-05-22

分享出去的网址播放地址改为了：https://aweme.snssdk.com/aweme/v1/playwm/?s_vid=93f1b41336a8b7a442dbf1c29c6bbc565bbe35281187d7253aac96d7894080039b53b6a0bf28394ad54eb32098a5ea0f3f00edf7f71b7d33a6626f3c673d9190&line=0

无法提取video_id

等待我近日重新捕获包了再看。

**Comment by paozhuanyinyu** [comment]
抖音分享链接更新了，没有video-id，连老版本抖音也获取不到无水印的短视频了

**Comment by fly-studio** [comment]
已经修正 2020-04-07
